# Take a Number
# Permissions:
# tan.ticket - Create help tickets
# tan.admin - Administrate tickets
# 
ShowTicketsOnJoin: true
NotifyAdminOnTicketClose: true
MaxTickets: 3
DateFormat: "dd/MMM/yy HH:mm"
AlwaysLoadTickets: true