name: TakeaNumber
main: me.olddragon.takeanumber.TakeaNumber
version: 0.8
commands:
   tan:
      description: Help Menu
      aliases: [tickethelp]
      permission:
      usage: /tan
   ticket:
      description: Open a help ticket
      permission: tan.ticket
      usage: /ticket <Description>
   tickets:
      description: review help tickets
      permission:
      usage: /tickets   
   closeticket:
      description: close a help ticket
      permission:
      usage: /closeticket <#>
   replyticket:
      description: reply to a help ticket
      permission: tan.admin
      usage: /replyticket <#> <reply>
   taketicket:
      description: review a help ticket
      permission: tan.admin
      usage: /taketicket <#>
   checkticket:
      description: check your own help ticket
      permission:
      usage: /checkticket <#>