# Take a Number
# Permissions:
# tan.ticket - Create help tickets
# tan.admin - Administrate tickets
# 
ShowTicketsOnJoin: true
NotifyAdminOnTicketClose: true
MaxTickets: 5
ResolvedTicketExpiration: 7
DateFormat: "yy-MM-dd HH:mm"
AlwaysLoadTickets: true
Messages:
   InvalidDateFormat:   "Invalid date format: %1$s"
   InvalidTicketFormat: "Invalid Ticket Format: %1$s"
   InvalidTicketNumber: "Invalid Ticket: %1$s"
   NoTickets:           "There are currently no tickets"
   ListHeading:         "-- Help Tickets --"
   ListEntry:           "(%1$s%2$s) %3$s: %1$s%4$s %5$s"
   TicketLimit:         "You have reached the limit for open tickets"
   OpenedTicket:        "Your ticket (#%1$d) has been logged and will be reviewed shortly. Use /ticket-check %1$d to review the status in the future."
   NotifyOpened:        "Ticket %1$d was opened by %2$s"
   ReplyTicket:         "* Replied to ticket %1$d."
   PlayerReply:         "* %1$s has replied to their ticket."
   AdminReply:          "* %1$s has replied to your ticket."
   ResolveTicket:       "Resolved ticket #%1$d."
   PlayerResolve:       "* %1$s has resolved to their ticket."
   AdminResolve:        "* %1$s has resolved to your ticket."
   AdminOnly:           "This command can only be used by administrators."
   TakeTicket:          "Administrator %1$s is reviewing ticket #%2$d."
   NoConsole:           "This command can not be run from the console."
   NotYourTicket:       "This ticket does not belong to you."
   OpenTickets:         "* There are currently %1$d open Help Tickets"
   DeleteTicket:        "Ticket %1$s was deleted."
   AdminDeleteTicket:   "* Administrator %1$s has deleted help ticket #%2$d"
   PlayerDeleteTicket:  "* %1$s has deleted their help ticket #%2$d"
   StartDeleteTickets:  "Deleting Expired Tickets"
   FinishDeleteTickets: "Deleted %1$d Expired Tickets"
   PlayerHelp:
     - "-- Commands --"
     - "/ticket-open <Description> - Open a ticket. (Location is tracked)"
     - "/ticket-list - View your tickets."
     - "/ticket-check <#> - Check one of your ticket's info."
     - "/ticket-reply <#> [message] - Reply to one of your tickets."
     - "/ticket-resolve <#> [message] - Resolve one of your tickets."
     - "/ticket-delete <#> - Delete one of your tickets."
   AdminHelp:
     - "-- Administrator Commands --"
     - "/ticket-list - List all tickets."
     - "/ticket-check <#> - Check a ticket's info."
     - "/ticket-take <#> - Assign yourself to a ticket."
     - "/ticket-visit <#> - Teleport yourself to a ticket location."
     - "/ticket-reply <#> [message] - Reply to a ticket."
     - "/ticket-resolve <#> [message] - Close a ticket."
     - "/ticket-delete <#> - Delete a ticket."
