name: TakeaNumber
main: me.olddragon.takeanumber.TakeaNumber
version: 0.2
commands:
   ticket-help:
      description: Help Menu
      aliases: [tickethelp]
      permission:
      usage: /<command>
   ticket-open:
      description: Open a help ticket
      aliases: [ticket, report]
      permission: tan.ticket
      usage: /<command> <Description>
   ticket-list:
      description: review help tickets
      aliases: [tickets]
      permission:
      usage: /<command>   
   ticket-check:
      description: close a help ticket
      permission:
      usage: /<command> <#>
   ticket-reply:
      description: reply to a help ticket
      permission: tan.admin
      usage: /<command> <#> <reply>
   ticket-take:
      description: review a help ticket
      permission: tan.admin
      usage: /<command> <#>
   ticket-resolve:
      description: resolve a help ticket
      permission: tan.admin
      usage: /<command> <#>